### 1. LÉPÉS: Hozz létre egy felhasználót
# A válaszban kapott "id"-t használd a következő kérésben!
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "golfoscigány@server.com",
    "name": "golfgusztáv",
    "password": "golfi"
}

### --------------------------------------------------

### 2. LÉPÉS: Hozz létre egy feladatot a felhasználóhoz
# Cseréld le a "userId" értékét az előző lépésben kapott ID-ra!
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "Vegyél tejet",
   "description": "2,8%-os",
    "userId": 2
}

### --------------------------------------------------

### 2. LÉPÉS: Hozz létre egy feladatot a felhasználóhoz
# Cseréld le a "userId" értékét az előző lépésben kapott ID-ra!
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "Házi feladat",
   "description": "Csináld meg!",
    "userId": 3
}

### --------------------------------------------------

### GET kérés az összes feladat lekérdezésére
GET http://localhost:3000/tasks


### --------------------------------------------------

### GET kérés az összes felhasználó lekérdezésére
GET http://localhost:3000/users

###

DELETE http://localhost:3000/tasks/2

### --------------------------------------------------

### Felhasználó törlése (és a hozzá tartozó feladatoké)
# FONTOS: Cseréld le a '2'-est a törölni kívánt felhasználó valós ID-jára!
DELETE http://localhost:3000/users/3

### --------------------------------------------------

### GET kérés a feladatok lapozott lekérdezésére (pl. 1. oldal)
GET http://localhost:3000/tasks/page/1

### --------------------------------------------------

